### ISSUE TITLE
Compilations problems on ubuntu trusty

### ISSUE THREAD

**Issue by SvensenSeven** [davidsblom/FOAM-FSI#355] opened 2016-09-19 04:53 UTC
There is some problem with BLAS (Ubuntu 14.04).

```
sergey@sergey-Notebook-PC:~/foam/foam-extend-3.2/FOAM-FSI/src/thirdParty$ ./Allmake 
+ '[' '!' -d boost_1_61_0 ']'
+ cd elemental
+ mkdir -p build install
+ cd build
+ '[' Opt = Opt ']'
++ pwd
+ cmake -D CMAKE_INSTALL_PREFIX=/home/sergey/foam/foam-extend-3.2/FOAM-FSI/src/thirdParty/elemental/build/../install -D INSTALL_PYTHON_PACKAGE=OFF -D CMAKE_BUILD_TYPE=Release -D EL_DISABLE_PARMETIS=TRUE -D CMAKE_CXX_COMPILER=g++ -D CMAKE_C_COMPILER=gcc -D CMAKE_Fortran_COMPILER=gfortran -D EL_DISABLE_SCALAPACK=TRUE -D 'MATH_LIBS=-L/usr/lib -lopenblas' ..
-- Appending /home/sergey/foam/foam-extend-3.2/FOAM-FSI/src/thirdParty/elemental/include for Elemental's source includes
-- Appending /home/sergey/foam/foam-extend-3.2/FOAM-FSI/src/thirdParty/elemental/build/include for Elemental's binary includes
-- CXX11_COMPILER_FLAGS=-std=gnu++11
-- Using __restrict__ keyword.
-- Will parse MPI header /usr/include/mpi.h
-- Using Open MPI version 2.0.1
-- Appending /usr/include for MPI headers
-- Using prespecified OpenMP_C_FLAGS=-fopenmp
-- Using prespecified OpenMP_CXX_FLAGS=-fopenmp
-- Valgrind Prefix: 
-- Could NOT find VALGRIND (missing:  VALGRIND_INCLUDE_DIR VALGRIND_PROGRAM) 
-- Will attempt to extend user-defined MATH_LIBS=-L/usr/lib -lopenblas
-- A library with BLAS API found.
-- A library with LAPACK API found.
CMake Error at cmake/external_projects/ElMath.cmake:329 (message):
  Could not determine BLAS format.
Call Stack (most recent call first):
  CMakeLists.txt:388 (include)


-- Configuring incomplete, errors occurred!
See also "/home/sergey/foam/foam-extend-3.2/FOAM-FSI/src/thirdParty/elemental/build/CMakeFiles/CMakeOutput.log".
See also "/home/sergey/foam/foam-extend-3.2/FOAM-FSI/src/thirdParty/elemental/build/CMakeFiles/CMakeError.log".
```
[CMakeError.txt](https://github.com/davidsblom/FOAM-FSI/files/479239/CMakeError.txt)
[CMakeOutput.txt](https://github.com/davidsblom/FOAM-FSI/files/479240/CMakeOutput.txt)

**Comment by davidsblom** [comment] 2016-09-19 06:10
I forgot to mention this in the README (and I'll add it), but you should install openblas.

On ubuntu `sudo apt-get install openblas` should do it.

Let me know how it goes

**Comment by SvensenSeven** [comment] 2016-09-19 07:16
The same problem with LAPACK

`-- A library with LAPACK API found.
-- Looking for daxpy
-- Looking for daxpy - not found
-- Looking for daxpy_
-- Looking for daxpy_ - found
-- Looking for dpotrf
-- Looking for dpotrf - not found
-- Looking for dpotrf_
-- Looking for dpotrf_ - not found
CMake Error at cmake/external_projects/ElMath.cmake:348 (message):
  Could not determine LAPACK format.
Call Stack (most recent call first):
  CMakeLists.txt:388 (include)


-- Configuring incomplete, errors occurred!
See also "/home/sergey/foam/foam-extend-3.2/FOAM-FSI/src/thirdParty/elemental/build/CMakeFiles/CMakeOutput.log".`


[CMakeError.txt](https://github.com/davidsblom/FOAM-FSI/files/479420/CMakeError.txt)
[CMakeOutput.txt](https://github.com/davidsblom/FOAM-FSI/files/479419/CMakeOutput.txt)

**Comment by davidsblom** [comment] 2016-09-19 07:18
Okay. Have you installed `liblapack-dev`?

**Comment by SvensenSeven** [comment] 2016-09-19 07:20
Yes,

`sergey@sergey-Notebook-PC:~/foam/foam-extend-3.2/FOAM-FSI$ sudo apt-get install liblapack-dev 
[sudo] password for sergey: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
liblapack-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 36 not upgraded.`

**Comment by davidsblom** [comment] 2016-09-19 07:24
hmm.. strange. Can you try removing the build directory: src/thirdParty/elemental/build
Maybe cmake uses an old configuration from before you installed openblas.

**Comment by SvensenSeven** [comment] 2016-09-19 08:29
I've done ./Allclean from FOAM-FSI and from src/thirdparty, but the result is the same.
Maybe it requires to install some additional package or maybe the version of Lapack in repository is too old ?

**Comment by davidsblom** [comment] 2016-09-19 08:41
okay. I've added a docker build using ubuntu trusty for the foam-fsi-docker repo. When this image is available (https://app.wercker.com/davidsblom/FOAM-FSI-docker/runs), I'll try to reproduce your problem.

In the mean time, you could try to build openblas and lapack yourselves by removing the line `-D MATH_LIBS="-L/usr/lib -lopenblas" \` from `src/thirdParty/compile_elemental`.

**Comment by SvensenSeven** [comment] 2016-09-20 05:26
I've tried to build openblas and lapack by myself according to your suggestion. Yes, it works !

However during the compilation of percice I've got an error:
`+ cd precice
+ '[' Opt = Opt ']'
+ scons -j 2 build=release python=off petsc=on compiler=mpicxx solib Symlink
./compile_precice: line 24: scons: command not found
sergey@sergey-Notebook-PC:~/foam/foam-extend-3.2/FOAM-FSI$ '

So, as you can see "scons" is missing. Please add to README that it is required to install "apt-get install scons". After installation of scons there is no problem

**Comment by SvensenSeven** [comment] 2016-09-20 05:28
Did you have a success in reproducing the problem with openblas ?

**Comment by davidsblom** [comment] 2016-09-20 07:21
`scons` needs to be added to the readme as well. Thanks!

I've just pushed commit 0db81327ce457b8c36c71a7a2aeae74e1ca3c14d, so it's now compiling and testing with wercker on ubuntu-trusty.
https://app.wercker.com/davidsblom/FOAM-FSI/runs

it's still in the queue, so let's see what happens.

**Comment by davidsblom** [comment] 2016-09-20 08:15
Apparent OpenMPI is not up to on ubuntu trusty. Which MPI library do you use?

**Comment by SvensenSeven** [comment] 2016-09-20 12:07
I use libopenmpi-dev and openmpi-bin packages. They were suggested for OpenFOAM compilation (http://openfoam.org/download/source/software-for-compilation/)

**Comment by davidsblom** [comment] 2016-09-20 12:10
Okay. And you successfully compiled elemental? I get the following error while compiling elemental.

```
cd elemental
+ mkdir -p build install
+ cd build
+ '[' Opt = Opt ']'
++ pwd
+ cmake -D CMAKE_INSTALL_PREFIX=/pipeline/source/src/thirdParty/elemental/build/../install -D INSTALL_PYTHON_PACKAGE=OFF -D CMAKE_BUILD_TYPE=Release -D EL_DISABLE_PARMETIS=TRUE -D CMAKE_CXX_COMPILER=g++ -D CMAKE_C_COMPILER=gcc -D CMAKE_Fortran_COMPILER=gfortran -D EL_DISABLE_SCALAPACK=TRUE -D 'MATH_LIBS=-L/usr/lib -lopenblas' ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Appending /pipeline/source/src/thirdParty/elemental/include for Elemental's source includes
-- Appending /pipeline/source/src/thirdParty/elemental/build/include for Elemental's binary includes
-- The Fortran compiler identification is GNU
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
-- Verifying Fortran/CXX Compiler Compatibility
-- Verifying Fortran/CXX Compiler Compatibility - Success
-- Performing Test _HAS_CXX11_FLAG
-- Performing Test _HAS_CXX11_FLAG - Success
-- Checking C++ support for "auto"
-- Checking C++ support for "auto": works
-- Checking C++ support for "class_override_final"
-- Checking C++ support for "class_override_final": works
-- Checking C++ support for "constexpr"
-- Checking C++ support for "constexpr": works
-- Checking C++ support for "cstdint_header"
-- Checking C++ support for "cstdint_header": works
-- Checking C++ support for "decltype"
-- Checking C++ support for "decltype": works
-- Checking C++ support for "defaulted_functions"
-- Checking C++ support for "defaulted_functions": works
-- Checking C++ support for "delegating_constructors"
-- Checking C++ support for "delegating_constructors": works
-- Checking C++ support for "deleted_functions"
-- Checking C++ support for "deleted_functions": works
-- Checking C++ support for "func_identifier"
-- Checking C++ support for "func_identifier": works
-- Checking C++ support for "initializer_list"
-- Checking C++ support for "initializer_list": works
-- Checking C++ support for "lambda"
-- Checking C++ support for "lambda": works
-- Checking C++ support for "long_long"
-- Checking C++ support for "long_long": works
-- Checking C++ support for "nullptr"
-- Checking C++ support for "nullptr": works
-- Checking C++ support for "rvalue_references"
-- Checking C++ support for "rvalue_references": works
-- Checking C++ support for "sizeof_member"
-- Checking C++ support for "sizeof_member": works
-- Checking C++ support for "static_assert"
-- Checking C++ support for "static_assert": works
-- Checking C++ support for "variadic_templates"
-- Checking C++ support for "variadic_templates": works
-- Found CXXFeatures: TRUE   
-- CXX11_COMPILER_FLAGS=-std=gnu++11
-- Performing Test EL_HAVE_TEMPLATE_ALIAS
-- Performing Test EL_HAVE_TEMPLATE_ALIAS - Success
-- Performing Test EL_HAVE_STEADYCLOCK
-- Performing Test EL_HAVE_STEADYCLOCK - Success
-- Performing Test EL_HAVE_NOEXCEPT
-- Performing Test EL_HAVE_NOEXCEPT - Success
-- Performing Test EL_HAVE_NORMAL_DIST
-- Performing Test EL_HAVE_NORMAL_DIST - Success
-- Performing Test EL_HAVE_UNIFORM_INT_DIST
-- Performing Test EL_HAVE_UNIFORM_INT_DIST - Success
-- Performing Test EL_HAVE_UNIFORM_REAL_DIST
-- Performing Test EL_HAVE_UNIFORM_REAL_DIST - Success
-- Performing Test EL_HAVE___restrict__
-- Performing Test EL_HAVE___restrict__ - Success
-- Performing Test EL_HAVE___restrict
-- Performing Test EL_HAVE___restrict - Success
-- Performing Test EL_HAVE_restrict
-- Performing Test EL_HAVE_restrict - Failed
-- Using __restrict__ keyword.
-- Performing Test EL_HAVE_PRETTY_FUNCTION
-- Performing Test EL_HAVE_PRETTY_FUNCTION - Success
-- Found MPI_C: /usr/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libhwloc.so  
-- Found MPI_CXX: /usr/lib/libmpi_cxx.so;/usr/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libhwloc.so  
-- Found MPI_Fortran: /usr/lib/libmpi_f90.so;/usr/lib/libmpi_f77.so;/usr/lib/libmpi.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libhwloc.so  
-- Performing Test EL_HAVE_MPI_REDUCE_SCATTER
-- Performing Test EL_HAVE_MPI_REDUCE_SCATTER - Success
-- Will parse MPI header /usr/lib/openmpi/include/mpi.h
CMake Error at cmake/detect/MPI.cmake:88 (message):
  Detected Open MPI version 1.6.5, but known bugs in version 1.6.5 of Open
  MPI have led Elemental to require at least version 1.8.1
Call Stack (most recent call first):
  CMakeLists.txt:356 (include)
```

**Comment by davidsblom** [comment] 2016-09-20 12:11
What is the output of `mpirun --version` on your machine?

**Comment by SvensenSeven** [comment] 2016-09-20 12:16
David, I've just forgot to tell you that I've also got such a problem. But I've downloaded the last version of OpenMPI and manually compiled it and install it to /usr. Therefore the output is:
```
sergey@sergey-Notebook-PC:~/foam/foam-extend-3.2/FOAM-FSI$ mpirun --version
mpirun (Open MPI) 2.0.1
```

**Comment by davidsblom** [comment] 2016-09-20 12:18
okay. thought so, I guess I'll have to do the same thing when building the images. Will need some time though since all the images will be rebuilt.

**Comment by SvensenSeven** [comment] 2016-09-20 12:19
I've got another error during compilation of FOAM-FSI itself. Do I need to open another issue or I can post it here ?

**Comment by davidsblom** [comment] 2016-09-20 12:20
you can post it here I guess

**Comment by SvensenSeven** [comment] 2016-09-20 12:21
```
sergey@sergey-Notebook-PC:~/foam/foam-extend-3.2/FOAM-FSI$ ./Allwmake
+++ dirname ./Allwmake
++ cd .
++ pwd
+ DIR=/home/sergey/foam/foam-extend-3.2/FOAM-FSI
+ cd /home/sergey/foam/foam-extend-3.2/FOAM-FSI
+ wmakeLnInclude src/boundaryConditions
+ wmakeLnInclude src/fvSchemes
+ wmakeLnInclude src/fsi
+ wmakeLnInclude src/RBFMeshMotionSolver
+ wmakeLnInclude src/SRFModelAbs
+ wmake libso src/boundaryConditions
'/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libboundaryConditions.so' is up to date.
+ wmake libso src/fvSchemes
'/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libfvSchemes.so' is up to date.
+ wmake libso src/fsi
'/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libfsi.so' is up to date.
+ wmake libso src/RBFMeshMotionSolver
'/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libRBFMeshMotionSolver.so' is up to date.
+ wmake libso src/SRFModelAbs
'/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libSRFModelAbs.so' is up to date.
+ wmake libso src/extraSolidBodyMotion
'/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libextraSolidBodyMotion.so' is up to date.
+ wmake applications/utilities/addInitialRandomVelocity
mpicxx -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3 -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG  -DNoRepository -ftemplate-depth-200 -I/home/sergey/foam/foam-extend-3.2/src/finiteVolume/lnInclude     -I/home/sergey/foam/foam-extend-3.2/src/meshTools/lnInclude -IlnInclude -I. -I/home/sergey/foam/foam-extend-3.2/src/foam/lnInclude -I/home/sergey/foam/foam-extend-3.2/src/OSspecific/POSIX/lnInclude   -fPIC -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPOpt/addInitialRandomVelocity.o -L/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt \
	     -lfiniteVolume     -lmeshTools -lfoam -liberty -ldl   -lrt -lm -o /home/sergey/foam/foam-extend-3.2/applications/bin/linux64GccDPOpt/addInitialRandomVelocity
/usr/bin/ld: warning: libdecompositionMethods.so, needed by /home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libmeshTools.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: liblagrangian.so, needed by /home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libmeshTools.so, not found (try using -rpath or -rpath-link)
/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libmeshTools.so: undefined reference to `Foam::decompositionMethod::New(Foam::dictionary const&)'
/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libmeshTools.so: undefined reference to `Foam::decompositionMethod::typeName'
/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libmeshTools.so: undefined reference to `Foam::Particle<Foam::passiveParticle>::typeName'
/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libmeshTools.so: undefined reference to `Foam::Cloud<Foam::passiveParticle>::typeName'
collect2: error: ld returned 1 exit status
make: *** [/home/sergey/foam/foam-extend-3.2/applications/bin/linux64GccDPOpt/addInitialRandomVelocity] Error 1
```

**Comment by davidsblom** [comment] 2016-09-20 12:23
I guess the compilation of foam-extend was not without problems. Can you paste the output of `Allwmake` in the folder `foam-extend-3.2`. That should give a hint what went wrong.

**Comment by SvensenSeven** [comment] 2016-09-20 12:37
It looks clean:
[foam_extend_log.txt](https://github.com/davidsblom/FOAM-FSI/files/482540/foam_extend_log.txt)

**Comment by SvensenSeven** [comment] 2016-09-20 12:38
I've just mentioned that while building thirdParty libs the Allwmake script cannot download CCMIO library, because it is unavailable on suggested URL link

**Comment by davidsblom** [comment] 2016-09-20 12:39
true, I have the same problem. That didn't pose any problems for me so far.

**Comment by davidsblom** [comment] 2016-09-20 12:41
so, the linker ld cannot find the libraries `libdecompositionMethods.so` and `liblagrangian.so`. So can you recompile those libraries, and libmeshTools also if you're recompiling stuff anyway ;-)

**Comment by davidsblom** [comment] 2016-09-20 12:42
and then check if the libraries are available in the folder $FOAM_LIBBIN

**Comment by SvensenSeven** [comment] 2016-09-20 12:44
I.e. I need to ./Allclean and ./Allwmake.firstInstall on foam-extend-3.2 ?

**Comment by davidsblom** [comment] 2016-09-20 12:45
that works, but then you'll recompile everything of foam-extend-3.2.

**Comment by davidsblom** [comment] 2016-09-20 12:46
you can also do 

```
foam-extend-3.2/src/decompositionMethods/decompositionMethods
wclean libso
```

**Comment by SvensenSeven** [comment] 2016-09-20 12:56
I've done:
```
sergey@sergey-Notebook-PC:~/foam/foam-extend-3.2/src/decompositionMethods/decompositionMethods$ wclean libso
wclean ./
sergey@sergey-Notebook-PC:~/foam/foam-extend-3.2/src/decompositionMethods/decompositionMethods$ cd ..
sergey@sergey-Notebook-PC:~/foam/foam-extend-3.2/src/decompositionMethods$ ./Allwmake
+ wmakeLnInclude decompositionMethods
wmakeLnInclude: linking include files to decompositionMethods/lnInclude
+ wmake libso decompositionMethods
wmakeLnInclude: linking include files to ./lnInclude
Making dependency list for source file decompositionMethod/decompositionMethod.C
Making dependency list for source file manualDecomp/manualDecomp.C
Making dependency list for source file simpleGeomDecomp/simpleGeomDecomp.C
Making dependency list for source file geomDecomp/geomDecomp.C
Making dependency list for source file patchConstrainedDecomp/patchConstrainedDecomp.C
Making dependency list for source file hierarchGeomDecomp/hierarchGeomDecomp.C
SOURCE=decompositionMethod/decompositionMethod.C ;  mpicxx -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3 -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG  -DNoRepository -ftemplate-depth-200  -IlnInclude -I. -I/home/sergey/foam/foam-extend-3.2/src/foam/lnInclude -I/home/sergey/foam/foam-extend-3.2/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/decompositionMethod.o
SOURCE=manualDecomp/manualDecomp.C ;  mpicxx -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3 -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG  -DNoRepository -ftemplate-depth-200  -IlnInclude -I. -I/home/sergey/foam/foam-extend-3.2/src/foam/lnInclude -I/home/sergey/foam/foam-extend-3.2/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/manualDecomp.o
SOURCE=geomDecomp/geomDecomp.C ;  mpicxx -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3 -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG  -DNoRepository -ftemplate-depth-200  -IlnInclude -I. -I/home/sergey/foam/foam-extend-3.2/src/foam/lnInclude -I/home/sergey/foam/foam-extend-3.2/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/geomDecomp.o
SOURCE=simpleGeomDecomp/simpleGeomDecomp.C ;  mpicxx -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3 -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG  -DNoRepository -ftemplate-depth-200  -IlnInclude -I. -I/home/sergey/foam/foam-extend-3.2/src/foam/lnInclude -I/home/sergey/foam/foam-extend-3.2/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/simpleGeomDecomp.o
SOURCE=hierarchGeomDecomp/hierarchGeomDecomp.C ;  mpicxx -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3 -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG  -DNoRepository -ftemplate-depth-200  -IlnInclude -I. -I/home/sergey/foam/foam-extend-3.2/src/foam/lnInclude -I/home/sergey/foam/foam-extend-3.2/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/hierarchGeomDecomp.o
SOURCE=patchConstrainedDecomp/patchConstrainedDecomp.C ;  mpicxx -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3 -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG -DNDEBUG  -DNoRepository -ftemplate-depth-200  -IlnInclude -I. -I/home/sergey/foam/foam-extend-3.2/src/foam/lnInclude -I/home/sergey/foam/foam-extend-3.2/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/patchConstrainedDecomp.o
'/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libdecompositionMethods.so' is up to date.
+ wmake libso metisDecomp
'/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libmetisDecomp.so' is up to date.
+ wmake libso parMetisDecomp
'/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libparMetisDecomp.so' is up to date.
+ wmake libso scotchDecomp
'/home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libscotchDecomp.so' is up to date.
sergey@sergey-Notebook-PC:~/foam/foam-extend-3.2/src/decompositionMethods$ 
```

**Comment by davidsblom** [comment] 2016-09-20 12:58
okay. looks good. you can also recompile liblagrangian and libmeshTools as indicated above.

**Comment by SvensenSeven** [comment] 2016-09-20 13:29
I attach the log for compilation of lib lagrangian, it contains several "not found" warnings (lines 93, 236, 254, 261, 322, 353).

The line 93 is interesting. It states that `/usr/bin/ld: warning: libdecompositionMethods.so, needed by /home/sergey/foam/foam-extend-3.2/lib/linux64GccDPOpt/libmeshTools.so, not found (try using -rpath or -rpath-link)`

However, I've just compile it. Also I've checked that this library is in $FOAM_LIBBIN
[lagrangian.txt](https://github.com/davidsblom/FOAM-FSI/files/482653/lagrangian.txt)

**Comment by davidsblom** [comment] 2016-09-20 13:32
okay. then I'm a bit lost here. I would then try to recompile the whole foam-extend-3.2 library.

**Comment by SvensenSeven** [comment] 2016-09-20 13:52
OK, it is quite long process, therefore I will do it during the night. In the morning I will inform you about the results

**Comment by SvensenSeven** [comment] 2016-09-21 04:41
I've recompiled foam-extend-3.2. Log file is attached. There was no obvious error during the compilation.

[foam_extend-3.2_build.txt](https://github.com/davidsblom/FOAM-FSI/files/484132/foam_extend-3.2_build.txt)

**Comment by SvensenSeven** [comment] 2016-09-21 07:21
David, is it possible to simply download already precompibled foam-extend-3.2.deb and compile FOAM-FSI with it ?

**Comment by davidsblom** [comment] 2016-09-21 07:40
cannot find any obvious problems either in the log. I don't know of any precompiled packages though. I have a docker image for foam-extend, but don't think that that's what you're looking for.

**Comment by SvensenSeven** [comment] 2016-09-21 07:48
The compiled deb package with foam-extend-3.2 is located here: https://sourceforge.net/projects/openfoam-extend/files/foam-extend-3.2/Ubuntu_14.04/

**Comment by davidsblom** [comment] 2016-09-21 07:49
ah oke. sounds good.

**Comment by SvensenSeven** [comment] 2016-09-21 07:50
how do you think is it possible to compile FOAM-FSI over it ?

**Comment by davidsblom** [comment] 2016-09-21 07:52
I haven't used that package so far. You only need the libraries itself, so if the foam-extend-3.2 environment is loaded, and the build system is available, you shouldn't have any problems.
only thing I'm worried about is the MPI library. I guess the package is compiled with a different version.

**Comment by SvensenSeven** [comment] 2016-09-21 07:55
Today I will try to compile FOAM-FSI with manually compiled foam-extend (I've sent to you a compilation log today). I will send you a result on Friday. Is it OK ?

**Comment by davidsblom** [comment] 2016-09-21 07:56
sure

**Comment by SvensenSeven** [comment] 2016-09-23 05:32
David, it seams that FOAM-FSI compiled successfully, however a lot of "could not open" messages appeared. I've just started the 3dTube tutorial and first iterations show no error.

However my home computer is too old, therefore fsiFoam occupied all RAM (2 Gb). That's why I could not completely test the correctness of compilation. I will try to compile and test FOAM-FSI on HP-workstation in our Biomedical Engineering department.

I think that in this evening I will send you a result
[fsi_foam_make.txt](https://github.com/davidsblom/FOAM-FSI/files/488943/fsi_foam_make.txt)

**Comment by davidsblom** [comment] 2016-09-23 05:57
Sounds good. I guess it compiled successfully.

Op vrijdag 23 september 2016 heeft Sergey <notifications@github.com> het
volgende geschreven:

**Comment by SvensenSeven** [comment] 2016-09-23 16:50
David, I've compiled foam-extend-3.2 and FOAM-FSI on HP workstation. All seams OK. I've tried to run 3dTube sample (it is close to my research task), but unfortunately I've got an error after first 50 iterations on the first temporal step. I've tried to check fsi library using testsuite-fsi - no errors, all tests are passed. I've changed nothing in the 3dTube tutorial. Settings were not modified.

I've attached all the logs below.
[foam-extend-make.txt](https://github.com/davidsblom/FOAM-FSI/files/490234/foam-extend-make.txt)
[fsi-foam-make.txt](https://github.com/davidsblom/FOAM-FSI/files/490235/fsi-foam-make.txt)
[log.blockMesh.txt](https://github.com/davidsblom/FOAM-FSI/files/490237/log.blockMesh.txt)
[log.checkMesh.txt](https://github.com/davidsblom/FOAM-FSI/files/490238/log.checkMesh.txt)
[log.decomposePar.txt](https://github.com/davidsblom/FOAM-FSI/files/490239/log.decomposePar.txt)
[log.fsiFoam.txt](https://github.com/davidsblom/FOAM-FSI/files/490236/log.fsiFoam.txt)
[log.renumberMesh.txt](https://github.com/davidsblom/FOAM-FSI/files/490240/log.renumberMesh.txt)

**Comment by davidsblom** [comment] 2016-09-23 17:18
Hi,

Apparently the coarsening strategy for the mesh deformation is not working
as it should. You can disable the coarsening in the file
fluid/constant/dynamicMeshDict.
Let me know how it goes.

Best,
David

Op vrijdag 23 september 2016 heeft Sergey <notifications@github.com> het
volgende geschreven:

**Comment by SvensenSeven** [comment] 2016-09-23 19:03
Yes, after disabling the coarsening it all works OK !!

Is it only my problem with coarsening or you have also problems when coarsening is enabled ?

**Comment by davidsblom** [comment] 2016-09-23 20:54
There is a known problem with the old RBF mesh deformation solver. The new
ElRBFMeshotionSolver works just fine.
I guess there is a tutorial with that mesh motion solver.

Let me know if you have further questions.

Op vrijdag 23 september 2016 heeft Sergey <notifications@github.com> het
volgende geschreven:

**Comment by SvensenSeven** [comment] 2016-09-23 20:59
Using Paraview I've just mentioned that only fluid/internalMesh domain is deforming while playing time animation. The solid/internalMesh stays rigid. Is it correct ?

**Comment by davidsblom** [comment] 2016-09-23 21:01
That's right. The mesh is fixed but you can show the displacement.
With warp vector button you can deform the solid mesh.

Op vrijdag 23 september 2016 heeft Sergey <notifications@github.com> het
volgende geschreven:

**Comment by SvensenSeven** [comment] 2016-09-23 21:03
Another short question. The outlet region seems to be rigid. Is it any way to make it deformable, like wall patch ?

**Comment by davidsblom** [comment] 2016-09-24 08:43
sure, you'll have to change the boundary conditions for the solid in solid/0/U. The fluid mesh should also be allowed to move I guess. Right now, it is a fixed patch in fluid/constant/dynamicMesh, and should be a moving patch.

**Comment by SvensenSeven** [comment] 2016-09-28 07:28
It seems that this issue can be closed

**Comment by davidsblom** [comment] 2016-09-28 11:25
Thanks. I'll close it when I have fixed the elemental compilation script. Still have some problems with the continuous integration test suite.

**Closed** 2016-09-30 15:10 UTC
