### ISSUE TITLE
preCICE. failed to restart

### ISSUE THREAD

**Issue by SvensenSeven** [davidsblom/FOAM-FSI#373] opened 2016-10-07 11:36 UTC
When trying to restart the previously stopped simulation, an error occurs like:
```
FOAM-FSI build: 3.2-73e514cebc1d

Patch outlet    Traction boundary field: U
        nonLinear set to total Lagrangian
Patch inner-wall        Traction boundary field: U
        nonLinear set to total Lagrangian
Patch outer-wall        Traction boundary field: U
        nonLinear set to total Lagrangian
[1]
[1]
[1] --> FOAM FATAL IO ERROR: [0]
[1] keyword grad(U_0) is undefined in dictionary "/home/sergey/foam/run/vessel-cylinder-initialized_by_pimple_fsiFoam-deformableOutlet/solid/processor1/../system/fvSchemes::gradSchemes"
[1]
[1] file: /home/sergey/foam/run/vessel-cylinder-initialized_by_pimple_fsiFoam-deformableOutlet/solid/processor1/../system/fvSchemes::gradSchemes from line 24 to line 25.
[1]
[1]     From function dictionary::lookupEntry(const word&, bool, bool) const
[1]     in file db/dictionary/dictionary.C at line 395.
[1]
FOAM parallel run exiting
[1]

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.
```

**Comment by davidsblom** [comment] 2016-10-07 11:38
should be fixed if you use this fvSolution file

the problem is that there is no default for the schemes.

```
/*--------------------------------*- C++ -*----------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | foam-extend: Open Source CFD                    |
|  \\    /   O peration     | Version:     3.0                                |
|   \\  /    A nd           | Web:         http://www.extend-project.de       |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      fvSchemes;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

d2dt2Schemes
{
    default backward2;
}

gradSchemes
{
    default extendedLeastSquares       0 ;
}

divSchemes
{
    default Gauss linear ;
}

laplacianSchemes
{
    default Gauss linear corrected 1;
}

snGradSchemes
{
    default corrected;
}

interpolationSchemes
{
    default linear;
}
```

**Comment by SvensenSeven** [comment] 2016-10-07 11:43
Thanks. It's working.

In the some tutorials (like 3dTube - master branch) the `default` is set to `none` like:
```
gradSchemes
{
    default none;
    grad(U) extendedLeastSquares       0 ;
}
```
So the other users can be faced with this problem in the future.

**Comment by davidsblom** [comment] 2016-10-07 11:44
Great. I'll update the tutorials, and close this issue.

**Closed** 2016-10-07 14:32 UTC
